[workspace]
members = ["apps/desktop/src-tauri", "crates/core", "crates/core-ffi"]
resolver = "2"

# 性能优先（默认）
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "unwind"
strip = "debuginfo"
split-debuginfo = "packed"

# 体积优先（按需手动指定）
[profile.release-small]
inherits = "release"
opt-level = "z"
