// @ts-check
/**
 * Lightweight Markdown → HTML converter (subset).
 *
 * Supports: headings, bold, italic, strikethrough, code blocks, inline code,
 * blockquotes, unordered/ordered lists, links, horizontal rules, images.
 *
 * Inspired by a CLI markdown renderer but adapted for browser HTML output.
 * Zero external dependencies.
 */

import { escapeHtml, sanitizeHtml } from './sanitize.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Convert a subset of Markdown to safe HTML.
 * Automatically strips the "📦 下载说明" / "Download" section.
 * @param {string} md - Raw Markdown text
 * @returns {string} HTML string
 */
export function markdownToHtml(md) {
    // --- Pre-processing: strip unwanted sections ---

    // Remove "📦 下载说明" / "Download" section and everything after it
    let processed = md.replace(/(?:^|\n)##\s*📦?\s*下载说明[\s\S]*$/i, '');
    processed = processed.replace(/(?:^|\n)##\s*📦?\s*Download[\s\S]*$/i, '');

    // --- Token-level processing (order matters) ---

    let html = processed;

    // Use placeholders for code blocks and inline code so that
    // escapeHtml in subsequent steps doesn't double-escape the generated HTML tags.
    /** @type {string[]} */
    const placeholders = [];

    // 1. Code blocks (```...```) — must be first to prevent inner content from being parsed
    html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_, _lang, code) => {
        const idx = placeholders.length;
        placeholders.push(`<pre class="bg-[var(--zephyr-bg-input)] rounded-[var(--zephyr-radius-surface)] p-3 my-3 text-xs overflow-x-auto leading-relaxed"><code>${escapeHtml(code.trimEnd())}</code></pre>`);
        return `\x00CODEBLOCK_${idx}\x00`;
    });

    // 2. Inline code — before bold/italic to avoid matching inside code
    html = html.replace(/`([^`]+)`/g, (_, code) => {
        const idx = placeholders.length;
        placeholders.push(`<code class="bg-[var(--zephyr-bg-input)] px-2 py-0.5 rounded text-xs align-middle">${escapeHtml(code)}</code>`);
        return `\x00INLINECODE_${idx}\x00`;
    });

    // 3. Escape HTML once globally — prevents XSS and avoids nested-formatting bugs
    //    where escapeHtml inside individual replacements would escape HTML tags
    //    generated by earlier replacements (e.g. *italic **bold** text*).
    html = escapeHtml(html);

    // 4. Headings (h1 > h2 > h3 to avoid h3 regex matching h2/h1)
    html = html.replace(/^### (.+)$/gm, (_, t) => `<h4 class="text-sm font-semibold text-[var(--text-primary)] mt-4 mb-1">${t}</h4>`);
    html = html.replace(/^## (.+)$/gm, (_, t) => `<h3 class="text-base font-semibold text-[var(--text-primary)] mt-5 mb-2">${t}</h3>`);
    html = html.replace(/^# (.+)$/gm, (_, t) => `<h2 class="text-lg font-bold text-[var(--text-primary)] mt-5 mb-2">${t}</h2>`);

    // 5. Blockquotes
    html = html.replace(/^&gt; (.+)$/gm, (_, t) => `<blockquote class="border-l-2 border-accent/40 pl-3 my-2 text-xs text-[var(--text-secondary)] italic">${t}</blockquote>`);

    // 6. Bold (before italic to avoid ** being partially consumed)
    html = html.replace(/\*\*(.+?)\*\*/g, (_, t) => `<strong class="font-semibold text-[var(--text-primary)]">${t}</strong>`);

    // 7. Italic
    html = html.replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, (_, t) => `<em>${t}</em>`);

    // 8. Strikethrough (~~text~~)
    html = html.replace(/~~(.+?)~~/g, (_, t) => `<del class="line-through text-[var(--text-muted)]">${t}</del>`);

    // 9. Horizontal rules
    html = html.replace(/^---$/gm, '<hr class="border-[var(--zephyr-border-default)] my-4">');

    // 10. Images — show alt text only (no actual img tag for security)
    html = html.replace(/!\[([^\]]*)\]\([^)]+\)/g, (_, alt) => `<span class="text-xs text-[var(--text-muted)]">[${alt}]</span>`);

    // 11. Links
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, text, href) => {
        // Block dangerous URI schemes
        if (/^\s*(javascript|vbscript|data)\s*:/i.test(href)) {
            return `<span class="text-xs text-[var(--text-secondary)]">${text}</span>`;
        }
        // Skip mailto links — show email as plain text
        if (href.startsWith('mailto:')) {
            return `<span class="text-xs text-[var(--text-secondary)]">${href.replace(/^mailto:/, '')}</span>`;
        }
        // href is already HTML-escaped from the initial escapeHtml pass;
        // only need to escape quotes for attribute context (avoid double-escaping &amp;)
        const safeHref = href.replace(/"/g, '&quot;').replace(/'/g, '&#39;');
        return `<a href="${safeHref}" class="text-accent underline" target="_blank" rel="noopener">${text}</a>`;
    });

    // 12. Unordered lists
    html = html.replace(/^(\s*)[-*] (.+)$/gm, (_, indent, t) => `${indent}<li class="ml-4 list-disc text-xs text-[var(--text-secondary)] leading-relaxed py-0.5">${t}</li>`);
    html = html.replace(/((?:<li[^>]*>.*<\/li>\n?)+)/g, '<ul class="my-3 space-y-2">$1</ul>');

    // 13. Ordered lists
    html = html.replace(/^\d+\. (.+)$/gm, (_, t) => `<li class="ml-4 list-decimal text-xs text-[var(--text-secondary)] leading-relaxed py-0.5">${t}</li>`);

    // 14. Paragraphs: wrap remaining loose lines that aren't already HTML tags or code block placeholders
    html = html.replace(/^(?!\s*<[a-z/]|\s*\x00CODEBLOCK)(.*\S.*)$/gm, (_, t) => `<p class="text-xs text-[var(--text-secondary)] leading-relaxed my-2">${t}</p>`);

    // --- Restore placeholders (before sanitizeHtml) ---
    html = html.replace(/\x00(?:CODEBLOCK|INLINECODE)_(\d+)\x00/g, (_, idx) => placeholders[parseInt(idx, 10)]);

    // --- Post-processing ---
    html = html.replace(/\n{3,}/g, '\n\n');

    return sanitizeHtml(html.trim());
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------
