export default [
  {
    ignores: ["node_modules/**", "src-tauri/**", "dist/**", "src/js-yaml.min.js"]
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        localStorage: "readonly",
        WebSocket: "readonly",
        URL: "readonly",
        Blob: "readonly",
        btoa: "readonly",
        atob: "readonly",
        jsyaml: "readonly",
        AbortController: "readonly",
        TextDecoder: "readonly",
        navigator: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        NodeList: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        CSS: "readonly",
        CustomEvent: "readonly",
        DOMException: "readonly",
        DOMParser: "readonly",
        Node: "readonly",
        DocumentFragment: "readonly",
        performance: "readonly",
        getComputedStyle: "readonly",
        alert: "readonly",
        confirm: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Object: "readonly",
        Array: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        clearTimeout: "readonly",
        setTimeout: "readonly",
        console: "readonly",
        queueMicrotask: "readonly",
        Intl: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        Symbol: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        WeakRef: "readonly",
        FinalizationRegistry: "readonly",
      }
    },
    rules: {
      "no-unused-vars": "off",
      "no-undef": "error"
    }
  }
];